/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigDisplay: typeof import('./components/plugin/ConfigDisplay.vue')['default']
    ConfigFormComponent: typeof import('./components/common/ConfigFormComponent.vue')['default']
    ConfigInputComponent: typeof import('./components/common/ConfigInputComponent.vue')['default']
    ConfigValueRenderer: typeof import('./components/plugin/config/ConfigValueRendererComponent.vue')['default']
    ConfirmComponent: typeof import('./components/common/ConfirmComponent.vue')['default']
    CreateHotSwapInfoDialog: typeof import('./components/hotSwap/CreateHotSwapInfoDialog.vue')['default']
    CreateSlotComponent: typeof import('./components/slot/CreateSlotComponent.vue')['default']
    CubeConfigComponent: typeof import('./components/plugin/CubeConfigComponent.vue')['default']
    CubeDetailsComponent: typeof import('./components/plugin/CubeDetailsComponent.vue')['default']
    CubeListItemComponent: typeof import('./components/plugin/CubeListItemComponent.vue')['default']
    ExtensionPackageDisplay: typeof import('./components/plugin/ExtensionPackageDisplay.vue')['default']
    FloatingBallComponent: typeof import('./components/world/FloatingBallComponent.vue')['default']
    FooterComponent: typeof import('./components/layout/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./components/layout/HeaderComponent.vue')['default']
    MinecraftButtonComponent: typeof import('./components/common/MinecraftButtonComponent.vue')['default']
    MinecraftInputComponent: typeof import('./components/common/MinecraftInputComponent.vue')['default']
    MonacoEditor: typeof import('./components/code/MonacoEditor.vue')['default']
    PluginStatisticsChart: typeof import('./components/plugin/PluginStatisticsChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./components/layout/SidebarComponent.vue')['default']
    SlotListItemComponent: typeof import('./components/slot/SlotListItemComponent.vue')['default']
    WorldListItemComponent: typeof import('./components/world/WorldListItemComponent.vue')['default']
    WorldPanelComponent: typeof import('./components/world/WorldPanelComponent.vue')['default']
  }
}
