/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmComponent: typeof import('./components/common/ConfirmComponent.vue')['default']
    CreateSlotComponent: typeof import('./components/slot/CreateSlotComponent.vue')['default']
    CubeDetail: typeof import('./components/plugin/CubeDetail.vue')['default']
    CubeDetailsComponent: typeof import('./components/plugin/CubeDetailsComponent.vue')['default']
    CubeListItemComponent: typeof import('./components/plugin/CubeListItemComponent.vue')['default']
    FooterComponent: typeof import('./components/layout/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./components/layout/HeaderComponent.vue')['default']
    MonacoEditor: typeof import('./components/code/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./components/layout/SidebarComponent.vue')['default']
    SlotListItemComponent: typeof import('./components/slot/SlotListItemComponent.vue')['default']
  }
}
